"""Metric domain models for the Sprint Health Dashboard (MR lag, deep work, estimation)."""

# class MrReviewLagRow(BaseModel): ...   # GitLab merge-request review lag
# class DeepWorkDay(BaseModel): ...
# class EstimationAccuracyRow(BaseModel): ...
