"""Metric domain models for the Sprint Health Dashboard (PR lag, deep work, estimation)."""

# class PrReviewLagRow(BaseModel): ...
# class DeepWorkDay(BaseModel): ...
# class EstimationAccuracyRow(BaseModel): ...
