"""Dependency-injection providers.

FastAPI `Depends` providers for shared clients and services. Centralizing construction here
keeps routes thin and makes the clients easy to mock in tests.
"""

# TODO: provide singletons / request-scoped instances, e.g.:
#   def get_bigquery_client() -> BigQueryClient: ...
#   def get_firestore_client() -> FirestoreClient: ...
#   def get_event_bus() -> EventBus: ...
#   def get_metrics_service(...) -> MetricsService: ...
